services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    env_file:
       - 'variables.env'
    depends_on:
      - db

  evaluator:
    build: ./evaluator
    depends_on:
      - db
    volumes:
      - evaluator-data:/var/lib/evaluator
    env_file:
       - 'variables.env'
    #restart: unless-stopped

  db:
    image: postgres:13
    env_file:
       - 'variables.env'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  evaluator-data:
