
[task]
name = "Sample Task"
template = "S_templates/sample.S"

description = '''
# SUBJECT TO CHANGE! Needs C file and cache settings.
# Your task description goes here (formatted in markdown).
## Use this as a template.
Starting memory is set by setting testcases.starting_mem, ending memory check is done by
setting testcases.reference_mem.
The ending values in registers are checked by setting testcases.reference_regs.
The scoring task is done by referencing the test name in the score.testcase field.
'''

[arguments]
run = "--d-regs --dump-cycles"

[[inputs]]
data_in = "Two values in memory starting at address 0x400."
data_out = "The values in registers, the sum in register a2, and the sum in memory after the two values."
description = "Loading of values from memory."

[[testcases]]
name = "test01"

[[testcases.reference_regs]]
a0 = 5
a1 = 10
a2 = 15

[[testcases.starting_mem]]
0x400 = 5
0x404 = 10

[[testcases.reference_mem]]
0x408 = 15

[[testcases]]
name = "test02"

[[testcases.starting_mem]]
0x400 = 150
0x404 = 200

[[testcases.reference_mem]]
0x408 = 350

[score]
description = "Runtime of the program in cycles."
testcase = "test01"
