[preprocessor]
vect_10 = "[random.randint(0, 100) for _ in range(10)]"
vect_10_s = "sorted(vect_10)"
vect_100 = "[random.randint(0, 100) for _ in range(100)]"
vect_100_s = "sorted(vect_100)"
vect_100_l = "[random.randint(5000, 10000) for _ in range(100)]"
vect_100_l_s = "sorted(vect_100_l)"
vect_23 = "[random.randint(0, 50) for _ in range(23)]"
vect_23_s = "sorted(vect_23)"

[task]
name = "Bubble Sort"
template = "S_templates/bubble.S"

description = '''
# Bubble Sort.
**Write a program that sorts an array using bubble sort algorithm.**

The size of the array will be located at the address `array_size`, the integer array (32-bit integer words) will start
at the address `array_start`.

The program should sort the array in ascending order.
Your program will be tested with different array sizes and different values in the array.

The complete task description can also be found [here](https://cw.fel.cvut.cz/wiki/courses/b35apo/en/homeworks/bonus/start), Makefile and template files for your own testing can be found on [GitLab](https://gitlab.fel.cvut.cz/b35apo/stud-support/-/tree/master/seminaries/qtrvsim/buble-sort).
'''

[arguments]
run = "--dump-cycles --cycle-limit 100000"

[[inputs]]
data_in = "Size of the array located at address array_size, the array start is located at the address array_start."
data_out = "Sorted array of length array_size"
description = "Cache optimized sorting."

[[testcases]]
name = "5 elements"

[[testcases.starting_mem]]
array_size = [5]
array_start = [1, 3, 4, 5, 2]

[[testcases.reference_mem]]
array_start = [1, 2, 3, 4, 5]

[[testcases]]
name = "10 elements"

[[testcases.starting_mem]]
array_size = [10]
array_start = "{{$vect_10$}}"

[[testcases.reference_mem]]
array_start = "{{$vect_10_s$}}"

[[testcases]]
name = "100 elements (random vector)"

[[testcases.starting_mem]]
array_size = [100]
array_start = "{{$vect_100$}}"

[[testcases.reference_mem]]
array_start = "{{$vect_100_s$}}"

[[testcases]]
name = "100 elements (random vector with large numbers)"

[[testcases.starting_mem]]
array_size = [100]
array_start = "{{$vect_100_l$}}"

[[testcases.reference_mem]]
array_start = "{{$vect_100_l_s$}}"

[[testcases]]
name = "private 1"
private = true

[[testcases.starting_mem]]
array_size = [10]
array_start = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

[[testcases.reference_mem]]
array_start = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

[[testcases]]
name = "private 2"
private = true

[[testcases.starting_mem]]
array_size = [7]
array_start = [47, 89, 48, 12, 45, 79, 34]

[[testcases.reference_mem]]
array_start = [12, 34, 45, 47, 48, 79, 89]

[[testcases]]
name = "private 3"
private = true

[[testcases.starting_mem]]
array_size = [23]
array_start = "{{$vect_23$}}"

[[testcases.reference_mem]]
array_start = "{{$vect_23_s$}}"

[[testcases]]
name = "scoring testcase"
private = true

[[testcases.starting_mem]]
array_size = [23]
array_start = [49789, 45633, 448, 1, 447, 9986, 1125, 44, 4, 8, 96, 2, 9, 7789, 44444, 55555, 66666, 99999, 77777, 6325, 1258, 12345, 54321]

[[testcases.reference_mem]]
array_start = [1, 2, 4, 8, 9, 44, 96, 447, 448, 1125, 1258, 6325, 7789, 9986, 12345, 44444, 45633, 49789, 54321, 55555, 66666, 77777, 99999]


[score]
description = "Runtime of the program in cycles."
testcase = "scoring testcase"
