[task]
name = "Example Task 3"

description = '''
# Radix sort

Write a **radix sort**.
'''

[[inputs]]
data_in = "9 8 7 6 5 4 3 2 1"
data_out = "1 2 3 4 5 6 7 8 9"
description = "Reversed sequence"

[[inputs]]
data_in = "4 9 6 4 7 8 5 1 5 5"
data_out = "1 4 4 5 5 5 6 7 8 9"
description = "Sequence with duplicates"